### ISSUE TITLE
[POSSIBLE CONFLICT: THERMAL] Gears (and possibly plates) produced using multiservo press are not usable in recipes

### ISSUE THREAD

**Issue by Cynix32** [SpaceXVI/More-Plates#16]
I have not extensively tested it yet, but it seems like MPR made the plates and gears produced using multiservo press unusable. The respective gear and plate outcome product were still the gears and plates from Thermal, instead of MPR. The items produced by the Multiservo press are then unusable in recipes due to how MPR replaces the recipes. 
Using Thermal 1.3 
on MC 1.16.5
utilizing Forge 36.2.2

**Comment by MostafaSabry55** [comment]
Hmmmm, This should not be happening, MPR's items use tags, and takes a high priority in recipes IF the recipe uses tags, so since thermal and all the other mods that add plates and tags for them, then this shouldn't be happening... as the recipes that use plates and gears should be using tags and not items.

I will try to make some tests to see why this is the case tho, thank you for informing me about this :)

**Comment by TrashboxBobylev** [comment]
You are overriding tags for them, that's why it doesn't work
![image](https://user-images.githubusercontent.com/22856970/140650141-d2d16e74-7638-47a7-a3c7-cd2c831f24ea.png)

**Comment by SpaceXVI** [comment]
Forgot to close this, I already fixed the replacing issue ages ago if I recall correctly
